"""Contraction graphs.

A fully-contracted scalar built from n copies of a p-form is a perfect
matching on the n*p index slots. The induced multigraph has every vertex of
valence p, and the multigraph determines the scalar up to sign.

So enumerating candidate invariants at order n is exactly:

    symmetric n x n non-negative integer matrices,
    zero diagonal, every row sum = p.

Pruning rules, both exact:
  * no self-loops -- contracting two slots of the same antisymmetric form
    gives zero;
  * m_ij <= p-1 FOR THE SELF-DUAL CASE ONLY -- multiplicity p between two
    vertices means those two forms fully contract, giving a factor F.F,
    which vanishes identically for a self-dual 5-form in 10D. For a
    GENERIC form (e.g. the 6D 3-form) F.F is a perfectly good invariant,
    so pass max_mult=valence there. This is the default.

Only CONNECTED graphs are kept: a disconnected graph is a product of lower
invariants and can never raise the Jacobian rank.

Dedup must be exact: a hash collision can drop a genuine contraction. Small
catalogs can be generated by the recursive Python enumerator below and
canonicalised with pynauty. Order 8 is generated directly without labelled
duplicates by nauty's geng | multig toolchain; see generate_graphs_nauty().
"""

import itertools
import json
import re
import subprocess
import numpy as np

try:
    import pynauty
except ImportError:  # pragma: no cover - exercised by the explicit error path
    pynauty = None


def _connected(M):
    n = M.shape[0]
    seen, stack = {0}, [0]
    while stack:
        v = stack.pop()
        for w in range(n):
            if w not in seen and M[v, w]:
                seen.add(w)
                stack.append(w)
    return len(seen) == n


def _canonical_exact(M):
    n = M.shape[0]
    iu = np.triu_indices(n, 1)
    best = None
    for perm in itertools.permutations(range(n)):
        key = tuple(M[np.ix_(perm, perm)][iu])
        if best is None or key < best:
            best = key
    return best


def _canonical_nauty(M):
    """Exact certificate for a multigraph via a colored incidence graph."""
    if pynauty is None:
        raise RuntimeError(
            "exact graph canonicalisation requires pynauty; "
            "install the packages in requirements.txt")

    n = M.shape[0]
    adjacency = {i: [] for i in range(n)}
    edge_vertices = set()
    next_vertex = n
    for i in range(n):
        for j in range(i + 1, n):
            multiplicity = int(M[i, j])
            for _ in range(multiplicity):
                edge_vertex = next_vertex
                next_vertex += 1
                edge_vertices.add(edge_vertex)
                adjacency[edge_vertex] = [i, j]
                adjacency[i].append(edge_vertex)
                adjacency[j].append(edge_vertex)

    # Parallel edges become interchangeable degree-2 incidence vertices.
    # The bipartition prevents original vertices and edge vertices from mixing.
    coloring = [set(range(n)), edge_vertices]
    graph = pynauty.Graph(
        number_of_vertices=next_vertex,
        directed=False,
        adjacency_dict=adjacency,
        vertex_coloring=coloring,
    )
    return pynauty.certificate(graph)


def canonical(M):
    """Exact isomorphism certificate."""
    if pynauty is not None:
        return _canonical_nauty(M)
    if M.shape[0] <= 6:
        return _canonical_exact(M)
    raise RuntimeError(
        "pynauty is required for exact canonicalisation above 6 vertices")


def enumerate_graphs(n, valence, max_mult=None, connected_only=True):
    """All valence-regular multigraphs on n vertices, deduped up to
    isomorphism.

    This labelled recursive generator is suitable for small n. Use
    generate_graphs_nauty() or a committed catalog for order 8.
    """
    if max_mult is None:
        max_mult = valence
    M = np.zeros((n, n), dtype=np.int64)
    out = {}

    def rec(i, j):
        if i == n - 1:
            if int(M[n - 1].sum()) != valence:
                return
            if connected_only and not _connected(M):
                return
            key = canonical(M)
            if key not in out:
                out[key] = M.copy()
            return
        if j == n:
            if int(M[i].sum()) != valence:
                return
            return rec(i + 1, i + 2)
        used_i = int(M[i].sum())
        used_j = int(M[j].sum())
        hi = min(max_mult, valence - used_i, valence - used_j)
        for m in range(hi + 1):
            M[i, j] = M[j, i] = m
            rec(i, j + 1)
        M[i, j] = M[j, i] = 0

    rec(0, 1)
    return list(out.values())


def graph_label(M):
    n = M.shape[0]
    separator = "-" if n > 10 else ""
    return f"n{n}[" + ",".join(
        f"{i}{separator}{j}^{int(M[i, j])}"
        for i in range(n) for j in range(i + 1, n)
        if M[i, j]) + "]"


def graph_from_label(label):
    """Inverse of graph_label.

    Labels through order 10 retain the historical compact ``ij^m`` syntax so
    committed result hashes remain stable. Higher orders use ``i-j^m`` to
    make multi-digit vertex numbers unambiguous.
    """
    match = re.fullmatch(r"n(\d+)\[(.*)\]", label)
    if not match:
        raise ValueError(f"invalid graph label: {label!r}")
    n = int(match.group(1))
    M = np.zeros((n, n), dtype=np.int64)
    body = match.group(2)
    if not body:
        return M
    edge_pattern = (
        r"(\d)-(\d)\^(\d+)"
        if n <= 10
        else r"(\d+)-(\d+)\^(\d+)"
    )
    legacy_pattern = r"(\d)(\d)\^(\d+)"
    for edge in body.split(","):
        edge_match = re.fullmatch(edge_pattern, edge)
        if edge_match is None and n <= 10:
            edge_match = re.fullmatch(legacy_pattern, edge)
        if not edge_match:
            raise ValueError(f"invalid edge in graph label: {edge!r}")
        i, j, multiplicity = map(int, edge_match.groups())
        if not (0 <= i < j < n) or multiplicity <= 0 or M[i, j]:
            raise ValueError(f"invalid or repeated edge: {edge!r}")
        M[i, j] = M[j, i] = multiplicity
    return M


def validate_graph(M, valence, max_mult, connected_only=True):
    """Raise ValueError unless M obeys all contraction-graph constraints."""
    M = np.asarray(M)
    if M.ndim != 2 or M.shape[0] != M.shape[1]:
        raise ValueError("adjacency matrix must be square")
    if not np.array_equal(M, M.T):
        raise ValueError("adjacency matrix must be symmetric")
    if np.any(np.diag(M)) or np.any(M < 0) or np.any(M > max_mult):
        raise ValueError("invalid diagonal or edge multiplicity")
    if not np.all(M.sum(axis=1) == valence):
        raise ValueError(f"every row must sum to {valence}")
    if connected_only and not _connected(M):
        raise ValueError("graph must be connected")


def _parse_multig_t(line):
    """Parse nauty multig's -T format: n ne {u v multiplicity}."""
    fields = [int(x) for x in line.split()]
    if len(fields) < 2 or len(fields[2:]) % 3:
        raise ValueError(f"invalid multig -T line: {line!r}")
    n, edge_count = fields[:2]
    if len(fields[2:]) != 3 * edge_count:
        raise ValueError(f"edge count mismatch in multig line: {line!r}")
    M = np.zeros((n, n), dtype=np.int64)
    for k in range(2, len(fields), 3):
        i, j, multiplicity = fields[k:k + 3]
        M[i, j] = M[j, i] = multiplicity
    return M


def graph_to_record(M):
    """Stable, unambiguous JSON record for a contraction graph."""
    M = np.asarray(M, dtype=np.int64)
    n = M.shape[0]
    return {
        "order": n,
        "upper_triangle": [
            int(M[i, j])
            for i in range(n)
            for j in range(i + 1, n)
        ],
    }


def graph_from_record(record):
    """Inverse of graph_to_record()."""
    n = int(record["order"])
    values = [int(x) for x in record["upper_triangle"]]
    if len(values) != n * (n - 1) // 2:
        raise ValueError("upper-triangle length does not match graph order")
    M = np.zeros((n, n), dtype=np.int64)
    k = 0
    for i in range(n):
        for j in range(i + 1, n):
            M[i, j] = M[j, i] = values[k]
            k += 1
    return M


def iter_graphs_nauty(n, valence, max_mult, geng="geng",
                      multig="multig", connected_only=True,
                      min_degree=None, max_degree=None,
                      residue=None, modulus=None):
    """Stream exact non-isomorphic multigraphs from nauty's gtools.

    geng supplies one copy of each underlying simple graph. multig assigns
    edge multiplicities, enforces regularity, and suppresses isomorphic
    weighted outputs. See the nauty User's Guide, section ``multig``.

    residue/modulus uses geng's exact canonical shard partition. Since the
    support graph of a multigraph is invariant under isomorphism, outputs from
    distinct support-graph shards are also disjoint.
    """
    geng_options = "-cq" if connected_only else "-q"
    geng_command = [geng, geng_options]
    if min_degree is not None:
        geng_command.append(f"-d{int(min_degree)}")
    if max_degree is not None:
        geng_command.append(f"-D{int(max_degree)}")
    geng_command.append(str(n))
    if (residue is None) != (modulus is None):
        raise ValueError("residue and modulus must be provided together")
    if modulus is not None:
        residue, modulus = int(residue), int(modulus)
        if modulus <= 0 or not 0 <= residue < modulus:
            raise ValueError("require 0 <= residue < modulus")
        geng_command.append(f"{residue}/{modulus}")

    producer = subprocess.Popen(
        geng_command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        consumer = subprocess.Popen(
            [multig, "-q", "-T", f"-m{max_mult}", f"-r{valence}"],
            stdin=producer.stdout,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except BaseException:
        producer.stdout.close()
        if producer.poll() is None:
            producer.terminate()
        producer.wait()
        producer.stderr.close()
        raise
    try:
        producer.stdout.close()
        for line in consumer.stdout:
            if not line.strip():
                continue
            M = _parse_multig_t(line)
            validate_graph(M, valence, max_mult, connected_only)
            yield M
    finally:
        if consumer.stdout is not None:
            consumer.stdout.close()
        multig_stderr = consumer.stderr.read()
        multig_status = consumer.wait()
        geng_stderr = producer.stderr.read().decode()
        geng_status = producer.wait()
    if geng_status:
        raise RuntimeError(
            f"geng failed ({geng_status}): {geng_stderr.strip()}")
    if multig_status:
        raise RuntimeError(
            f"multig failed ({multig_status}): {multig_stderr.strip()}")


def generate_graphs_nauty(n, valence, max_mult, geng="geng",
                           multig="multig", connected_only=True, **kwargs):
    """Materialize iter_graphs_nauty(); intended only for small catalogs."""
    return list(iter_graphs_nauty(
        n,
        valence,
        max_mult,
        geng=geng,
        multig=multig,
        connected_only=connected_only,
        **kwargs,
    ))


def load_graph_catalog(path, order):
    with open(path) as stream:
        catalog = json.load(stream)
    entry = catalog["orders"][str(order)]
    graphs = [graph_from_label(label) for label in entry["graphs"]]
    if len(graphs) != entry["count"]:
        raise ValueError(f"catalog count mismatch at order {order}")
    return graphs
