"""The M-only quotient rank, pinned.

Scalars built purely from M are generated by traces of its powers; with
tr(M) = 0 the complete degree-10 family is {tr(M^5), tr(M^3)tr(M^2)}. Both lie
entirely inside the reachable closure D_10, so the M-only quotient rank is 0
and every degree-10 quotient class requires at least one N channel.

The `status` assertions matter as much as the rank: a monomial that failed to
solve would also give rank 0, for an entirely uninformative reason. These
tests fail if the result becomes vacuous.
"""

import json
import os
from pathlib import Path
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

ROOT = Path(__file__).resolve().parents[1]
RESULT = (ROOT / "results" / "intrinsic_candidates"
          / "M_only_quotient_test_deg10.json")

EXPECTED_MONOMIALS = {"tr(M^5)", "tr(M^3)tr(M^2)"}


def _load():
    if not RESULT.exists():
        return None
    with RESULT.open() as stream:
        return json.load(stream)


def test_degree10_monomial_family_is_the_complete_partition_list():
    """Partitions of 5 with all parts >= 2, since tr(M) = 0."""
    payload = _load()
    if payload is None:
        return
    assert set(payload["monomials"]) == EXPECTED_MONOMIALS
    for powers in payload["monomials"].values():
        assert all(p >= 2 for p in powers), "tr(M)=0 forbids a part of size 1"
        assert sum(powers) == 5, "M-degree must be 5 at five-form degree 10"


def test_m_only_quotient_rank_is_zero_and_not_vacuous():
    payload = _load()
    if payload is None:
        return
    assert payload["consistent"] is True
    assert payload["M_only_quotient_rank"] == 0

    for prime, record in payload["per_prime"].items():
        projections = record.get("projections")
        assert projections, f"prime {prime}: no projections recorded"
        for name, proj in projections.items():
            # the non-vacuity condition: each monomial must actually SOLVE
            assert proj["status"] == "solved", (
                f"prime {prime}: {name} did not solve, so a rank of 0 would "
                f"be uninformative rather than a statement about the quotient")
            assert proj["nonzero_quotient"] is False
            assert all(v == 0 for v in proj["quotient_vector"])


def test_result_covers_fit_and_holdout_primes():
    payload = _load()
    if payload is None:
        return
    primes = {int(p) for p in payload["per_prime"]}
    assert len(primes) >= 5
    assert primes & set(payload["holdout_primes"]), (
        "at least one independent holdout prime must be present")
