#!/usr/bin/env python3
"""Write verification/SPINOR_JACOBIAN_STABILITY.md from the run artifacts.

The specification asks for a stability write-up alongside
`SPINOR_JACOBIAN_RUNS.json`. It is generated rather than written because every
number in it is already in the artifacts, and because two other hand-written
records in this repository went stale.

Sources:
  verification/SPINOR_JACOBIAN_RUNS.json   the two archived float64 runs
  results/rank81/certificate.json          the exact replacement
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "verification" / "SPINOR_JACOBIAN_RUNS.json"
CERT = ROOT / "results" / "rank81" / "certificate.json"
OUT = ROOT / "verification" / "SPINOR_JACOBIAN_STABILITY.md"


def fmt(x, digits=3):
    if x is None:
        return "--"
    if isinstance(x, float):
        return f"{x:.{digits}g}"
    return str(x)


def main() -> int:
    if not RUNS.exists():
        print(f"missing {RUNS.relative_to(ROOT)}")
        return 1
    d = json.loads(RUNS.read_text())
    runs = d["runs"]

    L = ["# Spinor Jacobian stability", "",
         "Generated by `scripts/emit_jacobian_stability.py`. Do not edit by hand.",
         "", d.get("method", ""), ""]

    if d.get("why_not_recomputed"):
        L += ["## Why these two runs and not a fresh matrix", "",
              d["why_not_recomputed"], ""]

    L += ["## Classification rule", "",
          "A run is **nondegenerate** only when every scheduled candidate row is",
          "meaningfully non-zero, the rank does not depend on an isolated",
          "tolerance, and the singular spectrum has a documented gap. A row at or",
          f"below the declared noise floor (relative `{d['noise_floor_relative']}`)",
          "is never normalised.", "",
          f"> {d.get('normalisation_rule','')}", "",
          "## The two archived runs", "",
          "| | " + " | ".join(r["label"] for r in runs) + " |",
          "|---|" + "---|" * len(runs)]

    rows = [
        ("seed", lambda r: r.get("seed")),
        ("scale", lambda r: r.get("scale")),
        ("finite-difference step", lambda r: r.get("step")),
        ("candidate ordering", lambda r: r.get("candidate_ordering")),
        ("row norm, min", lambda r: fmt(r.get("row_norm_min"))),
        ("row norm, median", lambda r: fmt(r.get("row_norm_median"))),
        ("row norm, max", lambda r: fmt(r.get("row_norm_max"))),
        ("rows at the noise floor", lambda r: r.get("n_zero_rows")),
        ("row normalisation", lambda r: r.get("row_normalisation")),
        ("rank, tolerance sweep", lambda r: "/".join(
            sorted({str(v) for v in r.get("tolerance_sweep", {}).values()}))),
        ("rank is tolerance-stable", lambda r: r.get("rank_is_tolerance_stable")),
        ("observed rank", lambda r: f"**{r.get('observed_rank')}**"),
        ("spectral gap at index 81", lambda r: fmt(r.get("gap_at_target"))),
        ("rank if the rule is broken", lambda r: (
            (r.get("if_normalisation_rule_is_broken") or {}).get("rank_if_rule_broken", "--"))),
        ("classification", lambda r: f"**{r.get('classification')}**"),
        ("artifact sha256", lambda r: f"`{str(r.get('sha256'))[:16]}...`"),
    ]
    for label, get in rows:
        L.append(f"| {label} | " + " | ".join(str(get(r)) for r in runs) + " |")

    nd = [r for r in runs if r["classification"] == "nondegenerate generic"]
    dg = [r for r in runs if r["classification"] == "degenerate sample"]
    L += ["", "## Reading the table", ""]
    if nd and dg:
        a, b = nd[0], dg[0]
        L += [
            f"The two runs are the same code at different random points. In "
            f"`{a['label']}` no row sits at the noise floor, the rank is the same "
            f"across the whole tolerance sweep, and the spectrum has a gap of "
            f"`{fmt(a['gap_at_target'])}` at index {a['target']}. Row normalisation "
            f"is legitimate there and the run supports rank {a['observed_rank']}.",
            "",
            f"In `{b['label']}`, {b['n_zero_rows']} of the scheduled rows evaluate "
            f"to numerical zero. Their surviving entries are rounding noise. The "
            f"gap at index {b['target']} is `{fmt(b['gap_at_target'])}` -- that is, "
            f"there is no gap -- so no tolerance choice is defensible, and the "
            f"honest rank is {b['observed_rank']}. Normalising the near-zero rows "
            f"rescales noise to unit length and reports "
            f"{(b.get('if_normalisation_rule_is_broken') or {}).get('rank_if_rule_broken')}, "
            f"which is fabricated.",
            "",
            "Both are kept. The degenerate run is the evidence that a genericity",
            "check is not optional, and deleting it would remove the reason the",
            "rule exists.",
            "",
        ]

    if CERT.exists():
        c = json.loads(CERT.read_text())
        s = c["summary"]
        sched = c["runs"][0]["schedule_summary"]
        L += ["## What replaced this computation", "",
              "The floating-point Jacobian is superseded by an exact analytic one.",
              "No step size, no rank tolerance, no row normalisation, and no",
              "classification rule is needed, because over `F_p` zero means zero.",
              "",
              f"    scheduled {sched['planned']}, evaluated "
              f"{sched['by_terminal_status'].get('evaluated', 0)}, "
              f"errors {sched['evaluation_errors']}, zero rows {sched['zero_rows']}",
              f"    exact modular rank {'/'.join(map(str, s['distinct_total_ranks']))}"
              f" at {s.get('n_points', s.get('n_runs'))} sample point(s)",
              f"    characteristic-zero lower bound {s['characteristic_zero_lower_bound']},"
              f" unconditional",
              "",
              "The float64 runs are retained as evidence about the *method*, not as",
              "support for the rank. See `docs/RANK81_EXACT_CERTIFICATE.md`.",
              ""]

    env = d.get("environment")
    if env:
        L += ["## Environment", "", "```", json.dumps(env, indent=1), "```", ""]

    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
