#!/usr/bin/env python3
"""Export the same fixed 81 ordered graph formulas used by the certificate."""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from sdinv.catalog import atomic_write_json
from sdinv.certificate import digest, validate_basis
from sdinv.contract import contraction_plan_profile
from sdinv.graphs import graph_from_label
from sdinv.latex import graph_to_latex, factor_lines
from sdinv.serialize import to_record


def export_basis():
    items, sources = [], {}
    for degree in (8, 10, 12):
        path = ROOT / "results" / f"10d_order{degree}.json"
        data = json.loads(path.read_text())
        sources[str(path.relative_to(ROOT))] = digest(data)
        for item in data["generators"]:
            if degree == 12 and not item["functional_increment"]:
                continue
            matrix = graph_from_label(item["graph"])
            record = to_record(matrix)
            items.append({"id": item["id"], "degree": item["order"],
                          "graph": record, "label": item["graph"],
                          "formula_sha256": digest(record),
                          "adjacency_matrix": matrix.tolist(),
                          "einstein_formula": graph_to_latex(matrix),
                          "contraction_cost": contraction_plan_profile(matrix, 10, 5)})
    manifest = {"schema": 1, "invariants": items, "sources": sources,
                "metric": [-1] + [1] * 9,
                "formula_convention": "Lexicographic edges and slots; incoming indices raised, outgoing indices lowered; one metric per edge.",
                "scope": "81 generically algebraically independent invariants; local generic coordinates, not global orbit separation or the full invariant ring."}
    validate_basis(manifest)
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(ROOT / "results/rank81_basis.json"))
    parser.add_argument("--latex-out", default=str(ROOT / "paper/tables/rank81_formulas.tex"))
    parser.add_argument("--certificate", type=Path, default=ROOT / "results/rank81_certificate.json")
    parser.add_argument("--cells-out", type=Path, default=ROOT / "paper/tables/certificate_cells.tex")
    args = parser.parse_args()
    manifest = export_basis()
    atomic_write_json(args.out, manifest)
    lines = ["% Generated by scripts/graph_to_latex.py; do not edit."]
    for item in manifest["invariants"]:
        matrix = graph_from_label(item["label"])
        lines += [rf"\paragraph{{\texttt{{{item['id'].replace('_', r'\_')}}}}}",
                  r"\begin{equation*}\begin{aligned}",
                  "&" + factor_lines(matrix), r"\end{aligned}\end{equation*}"]
    path = Path(args.latex_out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    if args.certificate.exists():
        certificate = json.loads(args.certificate.read_text())
        if certificate.get("complete") and certificate["basis_sha256"] == digest(manifest):
            cells = [r"\begin{center}\begin{tabular}{rrrr}",
                     r"\toprule Prime & Seed & Rank & $\det J_*\bmod p$\\\midrule"]
            for witness in certificate["witnesses"]:
                cells.append(f"{witness['prime']} & {witness['seed']} & {witness['rank']} & {witness['determinant_mod_p']}" + r"\\")
            cells.append(r"\bottomrule\end{tabular}\end{center}")
            args.cells_out.parent.mkdir(parents=True, exist_ok=True)
            args.cells_out.write_text("\n".join(cells) + "\n")
    print(f"Exported {len(manifest['invariants'])} formulas; basis SHA256 {digest(manifest)}")


if __name__ == "__main__":
    main()
