#!/usr/bin/env python3
"""Stage 2: the exact M-only quotient rank at degrees 10 and 12.

Scalars built purely from the symmetric matrix M are generated by traces of
its powers. Since M is quadratic in F, five-form degree 2k corresponds to
M-degree k, and tr(M) = 0 removes every partition part of size 1.

    degree 10  (M-degree 5):  tr(M^5), tr(M^3)tr(M^2)
    degree 12  (M-degree 6):  tr(M^6), tr(M^4)tr(M^2), tr(M^3)^2, tr(M^2)^3

Method, exact over F_p:

  1. build the atlas-basis value matrix at many generic samples;
  2. evaluate each M-trace monomial at the same samples;
  3. solve for the monomial's atlas coordinates (least-squares is NOT used --
     the system is solved exactly, and an inconsistent system is reported as
     such rather than approximated);
  4. project the coordinate vector into Q_d;
  5. report the rank of the projections.

A zero quotient rank would mean every quotient class requires at least one N
channel, which bounds the Level-B search. A nonzero rank would mean M-only
structures already reach part of the quotient. Both are reportable; neither is
assumed.
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from sdinv.modp import inv  # noqa: E402
from sdinv.forms import selfdual_projector, to_dense, random_form  # noqa: E402
from sdinv.contract import value  # noqa: E402
from sdinv.graphs import graph_from_label  # noqa: E402
from sdinv.stress import five_form_moment, matrix_trace_power  # noqa: E402
from sdinv.exactmap import rank_mod  # noqa: E402
from solve_intrinsic_quotients import rref, project  # noqa: E402
from stress_flow_closure import closure_span  # noqa: E402

CERT = ROOT / "results" / "stress_flow" / "certificates"
FIT_PRIMES = (32749, 32719, 32693, 32771, 32713)
HOLDOUT_PRIMES = (32717, 32687)
SEED8 = {4: ["I4_1"], 6: ["I6_2"], 8: ["I8_3", "I8_4", "I8_5", "I8_6"]}
DEG10 = ["I10_6", "I10_7", "I10_12"]

# partitions with all parts >= 2, since tr(M) = 0
M_MONOMIALS = {
    10: {"tr(M^5)": (5,), "tr(M^3)tr(M^2)": (3, 2)},
    12: {"tr(M^6)": (6,), "tr(M^4)tr(M^2)": (4, 2),
         "tr(M^3)^2": (3, 3), "tr(M^2)^3": (2, 2, 2)},
}


def registry_items():
    """id -> registry item, across all degrees the registry knows.

    The registry carries the graph label for every primitive AND the factor
    list for every product, which is what makes the product entries
    (I4_1*I6_1, I4_1*I6_2 at degree 10) evaluable rather than a dead end.
    """
    from sdinv.invariant_registry import load_verified_registry
    registry = load_verified_registry(str(ROOT))
    items = {}
    for degree in registry.degrees:
        for item in registry.basis(degree):
            items[item.id] = item
    return items


def evaluate_atlas_element(item, items, form, prime, cache, _seen=None):
    """Exact value of one atlas basis element on `form`.

    Primitives evaluate their graph; products multiply their factors, which is
    resolved recursively through the registry rather than assumed.

    Degree 12 stores `graph_record` rather than `graph`, so both are handled.
    `_seen` breaks self-reference: without it an item carrying neither field
    falls through to name parsing and recurses on itself until the stack dies,
    which is what happened on the first degree-12 run.
    """
    if item.id in cache:
        return cache[item.id]
    _seen = set() if _seen is None else _seen
    if item.id in _seen:
        raise ValueError(
            f"self-referential atlas element {item.id!r}: it has neither a "
            f"graph nor resolvable factors")
    _seen = _seen | {item.id}
    if getattr(item, "graph", None):
        g = graph_from_label(item.graph)
        out = value(g, form, 10, 5, True, prime) % prime
    elif getattr(item, "graph_record", None):
        from sdinv.graphs import graph_from_record
        g = graph_from_record(item.graph_record)
        out = value(g, form, 10, 5, True, prime) % prime
    elif getattr(item, "factors", ()):
        out = 1
        for factor in item.factors:
            out = (out * evaluate_atlas_element(
                items[factor], items, form, prime, cache, _seen)) % prime
    else:
        # product ids of the form 'A*B' or 'A^k' with no explicit factors
        name = item.id
        out = 1
        for piece in name.split("*"):
            if "^" in piece:
                base, power = piece.split("^")
                v = evaluate_atlas_element(
                    items[base], items, form, prime, cache, _seen)
                out = (out * pow(int(v), int(power), prime)) % prime
            else:
                out = (out * evaluate_atlas_element(
                    items[piece], items, form, prime, cache, _seen)) % prime
    cache[item.id] = out
    return out


def sample(prime, seed):
    projector = selfdual_projector(10, 5, True, prime)
    raw = random_form(10, 5, np.random.default_rng(seed), prime)
    return to_dense((projector @ raw) % prime, 10, 5, prime)


def m_monomial_value(form, powers, prime):
    _, mixed = five_form_moment(form, prime)
    out = 1
    for k in powers:
        out = (out * matrix_trace_power(mixed, k, prime)) % prime
    return out


def solve_exact(matrix, target, prime):
    """Solve A x = b exactly over F_p. Returns (x, consistent)."""
    rows = [list(r) + [t] for r, t in zip(matrix, target)]
    echelon, pivots = rref(rows, prime)
    ncols = len(matrix[0])
    for row in echelon:
        if all(v % prime == 0 for v in row[:ncols]) and row[ncols] % prime:
            return None, False
    x = [0] * ncols
    for row, piv in zip(echelon, pivots):
        if piv < ncols:
            x[piv] = row[ncols] % prime
    return x, True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--degree", type=int, required=True, choices=(10, 12))
    ap.add_argument("--out", type=Path)
    args = ap.parse_args()
    degree = args.degree

    items = registry_items()
    print(f"registry items available: {len(items)}")

    seed = dict(SEED8) if degree == 10 else {**SEED8, 10: DEG10}
    results = {}

    for prime in FIT_PRIMES + HOLDOUT_PRIMES:
        path = CERT / f"interacting_degree12_{prime}.json"
        if not path.exists():
            continue
        with path.open() as stream:
            certificate = json.load(stream)
        _, basis_map, span = closure_span(certificate, seed, prime)
        names = basis_map[degree]
        echelon, pivots = rref(span[degree], prime)
        free = [j for j in range(len(names)) if j not in set(pivots)]

        # value matrix: rows = samples, cols = atlas basis
        nsamp = len(names) + 8
        forms = [sample(prime, 30000 + 7 * i) for i in range(nsamp)]
        missing = [n for n in names if n not in items]
        if missing:
            print(f"  prime {prime}: atlas ids absent from registry: {missing}")
            results[prime] = {"status": "unresolved_ids", "missing": missing}
            continue
        cols = []
        for name in names:
            col = []
            for f in forms:
                col.append(evaluate_atlas_element(
                    items[name], items, f, prime, {}))
            cols.append(col)

        A = [[cols[j][i] for j in range(len(names))] for i in range(nsamp)]
        projections = {}
        for label, powers in M_MONOMIALS[degree].items():
            b = [m_monomial_value(f, powers, prime) for f in forms]
            x, ok = solve_exact(A, b, prime)
            if not ok:
                projections[label] = {"status": "not_in_atlas_span"}
                continue
            q = project(x, echelon, pivots, free, prime)
            projections[label] = {
                "status": "solved",
                "quotient_vector": q,
                "nonzero_quotient": any(v % prime for v in q),
            }
        vectors = [p["quotient_vector"] for p in projections.values()
                   if p.get("status") == "solved"]
        qrank = (rank_mod(np.asarray(vectors, dtype=np.int64) % prime, prime)
                 if vectors else 0)
        results[prime] = {"projections": projections, "M_only_quotient_rank": qrank}
        print(f"  prime {prime}: M-only quotient rank = {qrank} "
              f"(dim Q_{degree} = {len(free)})")

    ranks = {r.get("M_only_quotient_rank") for r in results.values()
             if "M_only_quotient_rank" in r}
    payload = {
        "schema": 1, "degree": degree,
        "monomials": {k: list(v) for k, v in M_MONOMIALS[degree].items()},
        "fit_primes": list(FIT_PRIMES), "holdout_primes": list(HOLDOUT_PRIMES),
        "per_prime": {str(k): v for k, v in results.items()},
        "consistent": len(ranks) == 1,
        "M_only_quotient_rank": (ranks.pop() if len(ranks) == 1 else None),
        "note": ("M-trace monomials with all parts >= 2, since tr(M)=0. "
                 "A zero rank bounds the Level-B search to N channels."),
    }
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n")
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
