"""Phase 9-10: how much does the stress-tensor trace sector actually reach?

The source literature writes the stress-tensor invariants of the ten-dimensional
self-dual five-form as traces of powers of

    M_mu{}^nu = F_{mu a b c d} F^{nu a b c d},

which is symmetric and traceless, hence has `D - 1 = 9` independent eigenvalues
and supplies the invariants `Tr M^n` for `n = 2, ..., 10`.

That is a strong constraint and it is dimension-dependent, which is exactly what a
cross-dimensional criterion needs.  This script measures, exactly and at several
primes:

  1. the graded dimension of the subspace generated by `M`-traces and their
     products at each degree;
  2. how that sits inside the full graded invariant space;
  3. how it sits inside the stress-flow-reachable sector `D10`.

The distinction being measured matters and is easy to blur: the *stress-tensor
trace subring* and the *stress-flow-reachable sector* are different objects. The
flow can reach more than the traces of `M` alone.  Reporting one as the other
would overstate the obstruction.
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "spinor_trace_bridge" / "src"))

from sdbridge.bridge import BridgeMap                      # noqa: E402
from sdbridge.comparison import trace_evaluation_matrix    # noqa: E402
from sdbridge.modular import matmul, rank as modrank, row_space_contains  # noqa: E402
from sdbridge.samples import build_registry, registry_hash  # noqa: E402
from sdbridge.tensor_words import TensorWordEvaluator      # noqa: E402
from sdbridge.traceside import load_registry               # noqa: E402


def m_trace_values(tw: TensorWordEvaluator, F_null_list, powers, p: int):
    """Tr M^n for each requested n, at every sample."""
    out = {n: [] for n in powers}
    for Fn in F_null_list:
        M = tw.M_tensor(Fn)
        acc = np.eye(M.shape[0], dtype=np.int64)
        for n in range(1, max(powers) + 1):
            acc = matmul(acc, M, p)
            if n in powers:
                out[n].append(int(np.trace(acc) % p))
    return {n: np.array(v, dtype=np.int64) % p for n, v in out.items()}


def monomials_of_degree(deg: int):
    """Products of Tr M^n with total F-degree `deg`.

    Tr M^n has F-degree 2n, so a monomial prod_i Tr M^{n_i} has degree
    2 * sum(n_i).  Partitions of deg/2 into parts >= 2 enumerate them.
    """
    if deg % 2:
        return []
    target = deg // 2

    def parts(remaining, minimum):
        if remaining == 0:
            yield ()
            return
        for k in range(minimum, remaining + 1):
            if k < 2:
                continue
            for rest in parts(remaining - k, k):
                yield (k,) + rest

    return [p for p in parts(target, 2)]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--primes", default="32749,32719")
    ap.add_argument("--degrees", default="4,6,8,10")
    ap.add_argument("--out", default=str(ROOT / "results" / "stress_flow" / "trace_sector.json"))
    args = ap.parse_args()

    primes = [int(x) for x in args.primes.split(",") if x.strip()]
    degrees = [int(x) for x in args.degrees.split(",") if x.strip()]
    registry = load_registry()

    report = {
        "schema": 1,
        "definition_M": "M_mu^nu = F_{mu abcd} F^{nu abcd}, symmetric and traceless",
        "why_D_minus_one": (
            "A symmetric traceless D x D matrix has D - 1 independent "
            "eigenvalues, so Tr M^n for n = 2..D exhausts the invariants "
            "obtainable from M alone. In D = 10 that is nine."),
        "distinction": (
            "The stress-tensor TRACE subring is not the stress-flow-reachable "
            "sector. The flow may reach more. Both are measured separately."),
        "primes": {},
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    for p in primes:
        t0 = time.time()
        b = BridgeMap(p=p)
        tw = TensorWordEvaluator(p=p)
        samples = build_registry(b)
        F_null = [b.frame.five_form_to_null(b.traceside_dense(s.as_array()))
                  for s in samples]
        max_pow = max(d // 2 for d in degrees)
        traces = m_trace_values(tw, F_null, list(range(2, max_pow + 1)), p)

        entry = {"n_samples": len(samples),
                 "registry_sha256": registry_hash(samples),
                 "per_degree": {}}
        for d in degrees:
            monos = monomials_of_degree(d)
            rows = []
            labels = []
            for m in monos:
                v = np.ones(len(samples), dtype=np.int64)
                for n in m:
                    v = (v * traces[n]) % p
                rows.append(v % p)
                labels.append(" * ".join(f"TrM^{n}" for n in m))
            Mrows = np.array(rows, dtype=np.int64) if rows else \
                np.zeros((0, len(samples)), dtype=np.int64)
            T = trace_evaluation_matrix(b, samples, registry, d)
            full = int(modrank(T, p))
            msec = int(modrank(Mrows, p)) if Mrows.size else 0
            union = int(modrank(np.concatenate([T, Mrows]), p)) if Mrows.size else full
            entry["per_degree"][str(d)] = {
                "monomials": labels,
                "n_monomials": len(labels),
                "M_trace_sector_rank": msec,
                "full_graded_rank": full,
                "union_rank": union,
                "M_sector_inside_full_space": bool(
                    row_space_contains(T, Mrows, p)) if Mrows.size else True,
                "codimension_of_M_sector": full - msec,
            }
        entry["wall_seconds"] = round(time.time() - t0, 1)
        report["primes"][str(p)] = entry
        for d, v in entry["per_degree"].items():
            print(f"[p={p} deg={d}] M-trace sector {v['M_trace_sector_rank']} "
                  f"of full {v['full_graded_rank']} "
                  f"(codim {v['codimension_of_M_sector']}, "
                  f"{v['n_monomials']} monomials)", flush=True)
        out.write_text(json.dumps(report, indent=1))

    first = report["primes"][str(primes[0])]["per_degree"]
    report["summary"] = {
        "graded_M_sector": {d: v["M_trace_sector_rank"] for d, v in first.items()},
        "graded_full": {d: v["full_graded_rank"] for d, v in first.items()},
        "graded_codimension": {d: v["codimension_of_M_sector"] for d, v in first.items()},
        "interpretation": (
            "Where the codimension is zero the M-trace sector already spans the "
            "graded piece. Where it is positive the stress-tensor traces alone "
            "cannot reach the whole space at that degree, independently of any "
            "flow."),
    }
    out.write_text(json.dumps(report, indent=1))
    print("done ->", out, json.dumps(report["summary"]["graded_codimension"]), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
